config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  get 'quotes', to: 'static_pages#quotes'
  get 'blog', to: 'static_pages#blog'
  get 'about', to: 'static_pages#about'

  get 'books', to: redirect('/')
  get '毛睿', to: redirect('/books/2')
  get 'test/:something', to: 'books#test', foo: 'bar'
  get 'request', to: 'books#showrequest'
  resources :books, constraints: { id: /\d+/ }, path_names: { edit: 'change' } do
    resources :quotes, only: [:index, :show]
  end

end

app/models/book.rb
require 'open-uri'

class Book < ActiveRecord::Base
  attr_accessor :douid

  has_many :quotes, dependent: :destroy
  validates :title, presence: true, uniqueness: true

  before_validation :fetch_douban_info

  private
  def fetch_douban_info
    title = self.title.split("(").first.strip if title
    if douid
      book_info = JSON.load(open "https://api.douban.com/v2/book/#{douid}")
      self.title = book_info["title"]
    else
      book_info = JSON.load(open "https://api.douban.com/v2/book/search?q=#{CGI.escape title}&count=1")["books"].first
    end
    self.author ||= book_info["author"].join(", ")
    self.description ||= book_info["summary"]
    self.image_url ||= book_info["images"]["small"]
    self.douban_url ||= book_info["alt"]
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :book
  validates :content,
    not_included_before: true, on: :create
  validates :content,
    presence: true

  before_create :destroy_subcontent_quotes

  private
  def destroy_subcontent_quotes
    Quote.where("position(content in ?) = 1", self.content).destroy_all
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # include ActionController::Live
  # force_ssl

  USERS = { "fanyange" => "zxTzq890806" }
  
  before_action -> { @book = Book.find(params[:id]) }, except: [:index, :showrequest]
  # before_action :authenticate

  def index
    @books = Book.includes(:quotes).order('quotes.created_at desc, books.created_at desc, books.updated_at desc')
    respond_to do |format|
      format.html
      format.xml { render xml: @books }
      format.json { render json: @books }
    end
  end

  def update
    original_url = @book.image_url
    f = params[:book][:image]
    path = Rails.root.join('app', 'assets', 'images', f.original_filename)
    File.open(path, 'wb') { |file| file.write f.read }
    File.delete(File.join(File.dirname(path), original_url)) rescue puts "Not a Uploaded image"
    if @book.update(image_url: f.original_filename)
      flash[:info] = "You have successfully uploaded a image file."
      redirect_to root_path
    else
      flash.now[:error] = "Your uploading failed."
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  def showrequest
    response.headers['Content-Type'] = 'text/event-stream'
    100.times do |i|
      response.stream.write "#{i+1} Hello World!\n"
      sleep 1
    end
  ensure
    response.stream.close
  end

  private

  def authenticate
    authenticate_or_request_with_http_digest do |username|
      USERS[username]
    end
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    if params[:book_id]
      @book = Book.find(params[:book_id])
      @quotes = @book.quotes.order(:start_loc)
    else
      @quotes = Quote.all
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def quotes
    @quotes = Quote.order(created_at: :desc)
    render 'quotes/index'
  end

  def blog
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
require "open-uri"

module BooksHelper
  def frequency_data
    # query = "select date, title as favorite, max(count) as max_count, sum(count) as sum_count from (select Date(quotes.created_at) as date, count(*) as count, title from quotes INNER JOIN books ON books.id = quotes.book_id group by Date(quotes.created_at), book_id) group by date;"

    count_quotes_by_day_and_book = "create temp view s1 as select Date(quotes.created_at) as date, count(*) as count, title from quotes INNER JOIN books ON books.id = quotes.book_id group by Date(quotes.created_at), title"
    max_and_sum_quotes_count_by_day = "create temp view s2 as select date, max(count) as max_count, sum(count) as sum_count from s1 group by date"
    query = "select s1.date,  max_count, sum_count from s2 inner join s1 on s2.date = s1.date and s2.max_count = s1.count"

    Quote.connection.select_all(count_quotes_by_day_and_book)
    Quote.connection.select_all(max_and_sum_quotes_count_by_day)
    Quote.connection.select_all(query)
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/_book.html.slim
= content_tag_for :tr, book do
  td = link_to image_tag(book.image_url, class: 'thumb'), edit_book_path(book)
  td =  link_to book.title , book.douban_url
  td = book.author
  td
    p = link_to button_tag("#{book.quotes.size} Quotes", class: 'ui inverted blue button'), book_quotes_path(book) 
    p = link_to button_tag('Show', class: 'ui inverted green button'), book 
    p = link_to button_tag('Delete', class: 'ui inverted red button'), book, method: :delete, data: { confirm: "Are you sure?" }

app/views/books/_chartkick.html.erb
<h1 class="header">Statistics</h1>
<%= line_chart Quote.group_by_week(:created_at).count %>
<%# <%= bar_chart [ %>
<%#   { %>
<%#     name: "Fantasy & Sci Fi", %> 
<%#     data: [["2010", 10], ["2020", 16], ["2030", 28]] %>
<%#   }, %>
<%#   { %>
<%#     name: "Romance", %> 
<%#     data: [["2010", 24], ["2020", 22], ["2030", 19]] %>
<%#   }, %>
<%#   { %>
<%#     name: "Mystery/Crime", %> 
<%#     data: [["2010", 20], ["2020", 23], ["2030", 29]] %>
<%#   } %>
<%# ] %1> %>

app/views/books/_try_ui.html.erb
<%= form_tag('/', class: "ui form", method: :get) do %>
  <div class="field"><%= text_field_tag :q, nil, placeholder: 'Input Text ...' %></div>
  <div class="inline fields">
    <div class="field">
      <div class="ui radio checkbox">
        <%= radio_button_tag :user_sex, "male" %>
        <%= label_tag :user_sex_male, "Male" %>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <%= radio_button_tag :user_sex, "female" %>
        <%= label_tag :user_sex_female, "Female" %>
      </div>
    </div>
  </div>
  <div class="ui checkbox field"><%= check_box_tag :remembered  %>
  <%= label_tag :remembered, "Remember Me" %></div>
  <div class="field"><%= submit_tag "Search", class: "ui button blue" %></div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<h2 class="ui dividing header"><%= @book.title %></h2>
<p><%= image_tag @book.image_url %></p>
<%= form_for @book, html: { class: "ui form" } do |f| %>
  <div class='field'><%= f.label "Upload A image for this book" %></div>
  <div class='field'><%= f.file_field :image %></div>
  <div class='field'><%= f.submit %></div>
<% end %>

app/views/books/index.html.erb
<%# <%= render "try_ui" %1> %>
<%# <%= content_tag :div, "", id: "frequency", data: {freq: frequency_data} %1> %>
<%= render "chartkick" %>
<h1 class="header">Index</h1>
<table class="ui celled table">
  <thead>
    <tr>
      <th>Thumbnail</th>
      <th>Title</th>
      <th>Author</th>
      <th>Actions</th>
    </tr>
  </thead> 
  <%= render @books %>
</table>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/books/showrequest.html.erb
<% request.methods.sort.each do |m| %>
  <%= content_tag(:p, m) %>
<% end %>

app/views/layouts/_flash.html.slim
- flash.each do |name, msg|
  .ui.message class=name
    i.close.icon
    .header
      | Message
    p = msg

app/views/layouts/_header.html.erb
<div class="ui inverted menu">
    <div class="ui container">
      <div class="header item">
        <h2 class="ui inverted grey header"><%= link_to "Kindle Quotes", root_path %></h2>
      </div>
      <%= link_to "Quotes", quotes_path, class: 'item' %>
      <%= link_to "Blog", blog_path, class: 'item' %>
      <%= link_to "About", about_path, class: 'item' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KindleQuotes</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://www.google.com/jsapi', 'chartkick' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main class="ui container">
    <%= render "layouts/flash" %>
    <%= yield %>
    <div id="footer" class="ui message warning">
      <%= debug(params) if Rails.env.development? %>
    </div>
    </main>
  </body>
</html>

app/views/quotes/_quote.html.slim
.ui.fluid.card
  .content
    p = quote.content
  .extra.content.ui.grid
    .ten.wide.column.special
      - if quote.notes 
        .note
          i.write.icon
          = quote.notes
    .six.wide.column.special
      span.right.floated.time
      i.calendar.icon
      = quote.created_at.strftime("%Y-%0m-%0d")

app/views/quotes/_select_book.html.slim
= form_for @book, html: { class: "ui form" } do |f|
  .two.fields
    .field
      = f.collection_select(:id, Book.all, :id, :title, {selected: nil, prompt: "Select A Book To Show Its Quotes"}, class: "ui search dropdown")

app/views/quotes/index.html.slim
- if @book
  .ui.segment#board
    h2 = @book.title
    = render 'select_book'

.ui.three.doubling.cards
  = render @quotes

app/views/static_pages/about.html.slim
h1.ui.header This is a site collecting kindle quotes.
p
  | This can do many things in the future.

app/views/static_pages/blog.html.slim
h1.ui.header This is my blog
p This is just the first sentence